# Tutorial n°1

## Electronic structure of water molecule

### Setup calculation

We start to ask a very simple calculation DFTB calculation : 

```deMon.inp
DFTB
```

Specify the path to Slater Koster parameters : 
```deMon.inp
PARAM PTYPE=NSC
∼ /basis
```

Enter a very simple geometry (non optimized) for water molecule with appropriate axis in XYZ coordinates :
```deMon.inp
GEOMETRY
O 0.0 0.0 0.0
H 0.0 0.75 0.0
H 0.0 0.0 0.75
```

Now, we have a complete input in deMon.inp.

### A. Run simple calculation

In [13]:
import deMonPy
deMonPy.configure_from_file("../global.json")

In [14]:
import numpy as np

symbols = ["O","H","H","O","H","H"]
positions = np.array(
            [[0.0,0.0,0.0],
            [0.0,0.75,0.0],
            [0.0,0.0,0.75]]
        )

In [15]:
from deMonPy.deMonNano import deMonNano

WORKDIR = ".run/tutorial-1/A/"

parameters = {
        "DEMON_EXECUTABLE":deMonPy.DEMON_EXECUTABLE,
        "BASIS":{
            "PTYPE":"NSC",
            "SKFILE":deMonPy.DEMON_BASIS
        },
        "DEMON_PARAMETERS":{
            "ACTIVE":{
                "DFTB":{
                },
            },
        }
    }

dem = deMonNano(
        title="CALCULATION DEMONANO",
        workdir=WORKDIR,
        **parameters
    )

dem.calculate(
        symbols=symbols,
        positions=positions
    )

 ✅ Loaded 2 elements from XYZ file.


In [16]:
print(
    f"Total energy : {dem.results['energy']}"
)

Total energy : {'energy': -3.88441215, 'electronic_energy': -4.59480449, 'band_energy': -4.59480449, 'repulsive_energy': 0.71039235, 'HOMO-LUMO_gap': 41.622, 'HOMO_gap': 2.84}


### B. SCC calculation

In [17]:
from deMonPy.deMonNano import deMonNano

WORKDIR = ".run/tutorial-1/B/"

parameters = {
        "DEMON_EXECUTABLE":deMonPy.DEMON_EXECUTABLE,
        "BASIS":{
            "PTYPE":"MAT",
            "SKFILE":deMonPy.DEMON_BASIS
        },
        "DEMON_PARAMETERS":{
            "ACTIVE":{
                "DFTB":{
                    "SCC":True
                },
            },
        }
    }

dem = deMonNano(
        title="CALCULATION DEMONANO",
        workdir=WORKDIR,
        **parameters
    )

dem.calculate(
        symbols=symbols,
        positions=positions
    )

 ✅ Loaded 2 elements from XYZ file.


In [18]:
print(
    f"Total energy : {dem.results['energy']}"
)

Total energy : {'energy': -3.92362655, 'electronic_energy': -4.55938324, 'band_energy': -4.56762717, 'repulsive_energy': 0.63575669, 'coulomb_energy': 0.00824393, '3d_coulomb_energy': 0.0, 'HOMO-LUMO_gap': 41.494, 'HOMO_gap': 2.956}


### C. Geometry optimization

In [19]:
from deMonPy.deMonNano import deMonNano

WORKDIR = ".run/tutorial-1/C/"

parameters = {
        "DEMON_EXECUTABLE":deMonPy.DEMON_EXECUTABLE,
        "BASIS":{
            "PTYPE":"BIO",
            "SKFILE":deMonPy.DEMON_BASIS
        },
        "DEMON_PARAMETERS":{
            "ACTIVE":{
                "DFTB":{
                    "SCC":True
                },
            },
        },
        "DEMON_MODULE":{
            "ACTIVE":{
                "OPT":{}
            }
        }
    }

dem = deMonNano(
        title="CALCULATION DEMONANO",
        workdir=WORKDIR,
        **parameters
    )

dem.calculate(
        symbols=symbols,
        positions=positions
    )

 ✅ Loaded 6 elements from XYZ file.


In [20]:
print(
    f"Total energy : {dem.results['energy']}"
)

optimized_geometry = dem.results["output_geometry"]
print("Optimized geometry : ",optimized_geometry)

Total energy : {'energy': -4.07518149, 'electronic_energy': -4.14856244, 'band_energy': -4.16833158, 'repulsive_energy': 0.07338096, 'coulomb_energy': 0.01976913, '3d_coulomb_energy': 0.0, 'HOMO-LUMO_gap': 17.871, 'HOMO_gap': 1.509}
Optimized geometry :  Atoms(symbols='OH2', pbc=False, initial_charges=...)


### D. Debug command and outputs

In [21]:
from deMonPy.deMonNano import deMonNano

WORKDIR = ".run/tutorial-1/D/"

parameters = {
        "DEMON_EXECUTABLE":deMonPy.DEMON_EXECUTABLE,
        "BASIS":{
            "PTYPE":"BIO",
            "SKFILE":deMonPy.DEMON_BASIS
        },
        "DEMON_PARAMETERS":{
            "ACTIVE":{
                "DFTB":{
                    "SCC":True
                },
                "PRINT":{
                    "DEBUG":True
                }
            },
        }
    }

dem = deMonNano(
        title="CALCULATION DEMONANO",
        workdir=WORKDIR,
        **parameters
    )

dem.calculate(
        symbols=optimized_geometry.symbols,
        positions=optimized_geometry.positions,
        extract_debug=True
    )

dem.print_results()

 ✅ Loaded 2 elements from XYZ file.
{
    "errors": [],
    "properties": {
        "scc_tolerance": 1e-08,
        "max_scc_cycles": 200,
        "scc_mixing": 0.3,
        "n_atoms": 3,
        "n_atom_types": 2,
        "matrix_dim": 6,
        "n_electrons": 8,
        "n_shells": 4
    },
    "energy": {
        "energy": -4.07518111,
        "electronic_energy": -4.14834061,
        "band_energy": -4.16811484,
        "repulsive_energy": 0.07315949,
        "coulomb_energy": 0.01977424,
        "3d_coulomb_energy": 0.0,
        "HOMO-LUMO_gap": 17.842,
        "HOMO_gap": 1.512
    },
    "moe": {
        "occupied": [
            -0.8496,
            -0.4167,
            -0.3141,
            -0.2585
        ],
        "virtual": [
            0.3972,
            0.5566
        ]
    },
    "mos": {
        "n_atoms": 3,
        "n_basis": 6,
        "parameter_type": "BIO",
        "homo": 4,
        "lumo_range": [
            1,
            6
        ],
        "atoms": [
    

In [22]:
print(dem.results.keys())

dict_keys(['errors', 'properties', 'energy', 'moe', 'mos', 'tensors', 'Gamma', 'Overlaps', 'Ham0', 'Hamiltonian', 'Density', 'Coefficients', 'input_geometry', 'output_geometry'])


Display of final matrix obtained from DEBUG keyword (all the steps are read and stored) : 

In [23]:
print("Hamiltonian-0 : \n",dem.results["Ham0"][0])
print("Overlaps : \n",dem.results["Overlaps"][0])
print("Gamma : \n",dem.results["Gamma"])

Hamiltonian-0 : 
 [[-0.878832  0.        0.        0.       -0.494126 -0.494126]
 [ 0.       -0.332132  0.        0.        0.        0.      ]
 [ 0.        0.       -0.332132  0.       -0.335831  0.05062 ]
 [ 0.        0.        0.       -0.332132  0.05062  -0.335831]
 [-0.494126  0.       -0.335831  0.05062  -0.2386   -0.107113]
 [-0.494126  0.        0.05062  -0.335831 -0.107113 -0.2386  ]]
Overlaps : 
 [[ 1.        0.        0.        0.        0.419705  0.419705]
 [ 0.        1.        0.        0.        0.        0.      ]
 [ 0.        0.        1.        0.        0.385786 -0.05815 ]
 [ 0.        0.        0.        1.       -0.05815   0.385786]
 [ 0.419705  0.        0.385786 -0.05815   1.        0.179391]
 [ 0.419705  0.       -0.05815   0.385786  0.179391  1.      ]]
Gamma : 
 [[0.5222  0.39359 0.39359]
 [0.39359 0.47    0.30137]
 [0.39359 0.30137 0.47   ]]


In [25]:
print("Hamiltonian final : \n",dem.results["Hamiltonian"][-1])
print("Density : \n",dem.results["Density"][-1])
print("Coefficients : \n",dem.results["Coefficients"][-1])

Hamiltonian final : 
 [[-0.805215  0.        0.        0.       -0.477727 -0.477727]
 [ 0.       -0.258514  0.        0.        0.        0.      ]
 [ 0.        0.       -0.258514  0.       -0.320757  0.048348]
 [ 0.        0.        0.       -0.258514  0.048348 -0.320757]
 [-0.477727  0.       -0.320757  0.048348 -0.234073 -0.106301]
 [-0.477727  0.        0.048348 -0.320757 -0.106301 -0.234073]]
Density : 
 [[ 1.604186  0.       -0.352098 -0.352098  0.149723  0.149723]
 [ 0.        2.        0.        0.        0.        0.      ]
 [ 0.        0.        1.179119  0.334959  0.610348 -0.115162]
 [ 0.        0.        0.        1.179119 -0.115162  0.610348]
 [ 0.        0.        0.        0.        0.441453 -0.182084]
 [ 0.        0.        0.        0.        0.        0.441453]]
Coefficients : 
 [[-1.201203  0.        0.401619  0.        0.        0.      ]
 [ 0.        0.        0.        1.414214  0.        0.      ]
 [ 0.002213  0.649677 -0.870077  0.        0.        0.      ]
 [